version: '3.9'

services:
  # Pimlico Infra (Node + Paymaster + Bundler)
  anvil:
    image: ghcr.io/foundry-rs/foundry:master
    ports: [ "8545:8545" ]
    entrypoint: [ "anvil", "--host", "0.0.0.0" ]
    platform: linux/amd64/v8

  mock-paymaster:
    image: ghcr.io/pimlicolabs/mock-verifying-paymaster:main
    ports: [ "3000:3000" ]
    environment:
      - ALTO_RPC=http://alto:4337
      - ANVIL_RPC=http://anvil:8545

  alto:
    image: ghcr.io/pimlicolabs/mock-alto-bundler:main
    ports: [ "4337:4337" ]
    environment:
      - ANVIL_RPC=http://anvil:8545
      - ALTO_BALANCE_OVERRIDE=false
